// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ogefdjkljlfhlfntngss.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9nZWZkamtsamxmaGxmbnRuZ3NzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3NDAwMTgsImV4cCI6MjA2MDMxNjAxOH0.bvykzHjqnNomXN9BcCVBWOW6F1h6mu4gaCx8StfR1TQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);